#!/bin/bash
set -euo pipefail

# generate-deep-dive.sh - Generate markdown deep-dive from analysis
# Usage: ./generate-deep-dive.sh [phase-name] [files...]
# Exit codes: 0 success, 1 usage error, 2 file error

source "$(dirname "$0")/config.sh"

PHASE_NAME="${1:-code-analysis}"
shift 2>/dev/null || true
FILES=("$@")

TIMESTAMP=$(date +"$ANTIVIBE_DATE_FORMAT")
OUTPUT_DIR="$ANTIVIBE_OUTPUT_DIR"
OUTPUT_FILE="$OUTPUT_DIR/${PHASE_NAME}-${TIMESTAMP}.md"

# Create output directory
if ! mkdir -p "$OUTPUT_DIR" 2>/dev/null; then
    log_error "Cannot create output directory: $OUTPUT_DIR"
    exit 2
fi

# Check for existing file with same phase name (today)
TODAY=$(date +%Y-%m-%d)
EXISTING=$(find "$OUTPUT_DIR" -name "${PHASE_NAME}-${TODAY}*" -type f 2>/dev/null | head -1)
if [ -n "$EXISTING" ]; then
    log_warn "Existing deep-dive found: $EXISTING"
    log_info "Creating new version with timestamp"
fi

log_info "Generating deep-dive: $OUTPUT_FILE"
echo ""

# Build the file header
cat > "$OUTPUT_FILE" << EOF
# Deep Dive: $PHASE_NAME

**Generated**: $(date '+%Y-%m-%d %H:%M:%S')
**Phase**: $PHASE_NAME
**Files analyzed**: ${#FILES[@]}

---

## Overview

### What This Code Does

_Describe the functionality in plain language._

### Why This Approach Was Taken

_Explain the design decisions and trade-offs._

### Context

_When would you use this? What problems does it solve?_

---

## Code Walkthrough

EOF

# Process each file - auto-populate with analysis data
for FILE in "${FILES[@]}"; do
    if [ -f "$FILE" ]; then
        BASENAME=$(basename "$FILE")
        EXTENSION="${FILE##*.}"
        LINES=$(wc -l < "$FILE" 2>/dev/null || echo "0")

        cat >> "$OUTPUT_FILE" << EOF
### $BASENAME

**Path**: \`$FILE\`
**Lines**: $LINES
**Language**: $EXTENSION

**Purpose**: _What this file handles_

**Key Components**:
EOF

        # Auto-extract structure using analyze-code.sh
        if [ -x "$ANTIVIBE_SCRIPTS/analyze-code.sh" ]; then
            ANALYSIS=$("$ANTIVIBE_SCRIPTS/analyze-code.sh" "$FILE" 2>/dev/null || true)
            # Extract function/class names from analysis
            FUNCTIONS=$(echo "$ANALYSIS" | grep -A 50 "^Functions:" | grep -E "^[[:space:]]*(export|pub|def|func|function|class|const|async)" | head -5 || true)
            if [ -n "$FUNCTIONS" ]; then
                echo "" >> "$OUTPUT_FILE"
                echo '```' >> "$OUTPUT_FILE"
                echo "$FUNCTIONS" >> "$OUTPUT_FILE"
                echo '```' >> "$OUTPUT_FILE"
            fi
        fi

        echo "" >> "$OUTPUT_FILE"
        echo "---" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    else
        log_warn "File not found, skipping: $FILE"
    fi
done

# Add concepts section
cat >> "$OUTPUT_FILE" << 'EOF'

## Concepts Explained

### Design Patterns Used

| Pattern | Where Used | Why |
|---------|------------|-----|
| _Pattern name_ | _File/function_ | _Design rationale_ |

### Key Technical Concepts

#### Concept 1

**What**: _Plain-language explanation_

**Why Used Here**: _Design decision explanation_

**When to Use**: _Appropriate contexts_

**Trade-offs**:
- Pros: _What you gain_
- Cons: _What you give up_

**Alternatives**:
- _Alternative 1_: _Brief comparison_

---

## Learning Resources

### Official Documentation

- [_Doc Name_](URL): _What you'll learn here_

### Tutorials & Articles

- [_Article Title_](URL): _Why this is helpful_

### Videos

- [_Video Title_](URL): _What it covers_

---

## Related Code in This Project

| File | Relationship |
|------|--------------|
| _related-file_ | _How it connects_ |

---

## Next Steps

1. **Try it yourself**: _Hands-on exercise suggestion_
2. **Deeper dive**: _Advanced topics to explore_
3. **Common pitfalls**: _Things to watch out for_

---

*Generated by [AntiVibe](https://github.com/mohi-devhub/antivibe) - Learn what AI writes, not just accept it.*
EOF

log_success "Generated: $OUTPUT_FILE"
log_info "Edit this file to add your specific analysis."
